services:

  wordpress:
    image: wordpress:6.8.0-php8.3-fpm
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: reyan
      WORDPRESS_DB_PASSWORD: Reyane@01
      WORDPRESS_DB_NAME: word
    volumes:
      - wp_files:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: word
      MYSQL_USER: reyan
      MYSQL_PASSWORD: Reyane@01
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
  nginx:
     image: nginx:alpine
     depends_on:
      - wordpress
     ports:
      - 8085:80
     volumes:
      - ./conf.d:/etc/nginx/conf.d
      - wp_files:/var/www/html

volumes:
  db:
  wp_files:
